version: '3.8'

networks: 
  private:
    external:
      name: private
  web:
    external: 
      name: web

services:      
  node:
    build: node.Dockerfile
    container_name: nodejs
    networks:  
      - private
      - web
    user: 0:0

  server:
    build: nginx.Dockerfile
    container_name: front-app
    networks:  
      - private
      - web
    user: 0:0
    labels:
      - traefik.enable=true
      - "traefik.http.routers.front.entrypoints=websecure"
      - traefik.http.routers.front.rule=Host(`dsp4-5archio19-ah-je-gh-yb.fr`)
      - "traefik.http.routers.front.tls.certresolver=lets-encr"

