version: '3.8'

networks: 
  private:
    external:
      name: private
  web:
    external: 
      name: web

services:      
  server:
    build: .
    container_name: front-app
    networks:  
      - private
      - web

