version: '3.8'

networks: 
  private:
    external:
      name: private
  web:
    external: 
      name: web

services:      
  front:
    build: .
    container_name: front-app
    networks:  
      - private
      - web
    user: 0:0
    labels:
      - traefik.enable=true
      - "traefik.http.routers.front.entrypoints=websecure"
      - traefik.http.routers.front.rule=Host(`dsp4-5archio19-ah-je-gh-yb.fr`)
      - "traefik.http.routers.front.tls.certresolver=lets-encr"
      - traefik.front.headers.customResponseHeaders=Access-Control-Allow-Origin:*
      - traefik.front.headers.Access-Control-Allow-Methods=GET, POST, OPTIONS
      - traefik.front.headers.Access-Control-Allow-Headers=DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
    


